######################################################### Tracks ##################################################################

###Listar de Tracks
GET http://localhost:3001/api/tracks

#### Crear Track     NOTE: el mediaId se toma del id generado al subir el archivo con storage

POST http://localhost:3001/api/tracks
Content-Type: application/json

{
  "name": "Arfhel",
  "album": "Album",
  "cover": "http://tttt.com",
  "artist": {
    "name": "Arfhel",
    "nickname": "Arfhel V",
    "nationality": "Mxn"
  },
  "duration":{
    "start": 1,
    "end": 0
  },
  "mediaId": "65c421c8f7da2f76d34633d3"
}

###Tracks prueba de limpia de datos recibidos en la request

POST http://localhost:3001/api/tracks
Content-Type: application/json

{
  "dato":"basura",
  "name": "Arfhel",
  "album": "Album",
  "cover": "http://tttt.com",
  "artist": {
    "name": "Arfhel",
    "nickname": "Arfhel V",
    "nationality": "Mxn"
  },
  "duration":{
    "start": 1,
    "end": 0
  },
  "mediaId": "621e7499a1f699063f5114bc" 
}


###Tracks middleware con custom headers prueba

POST http://localhost:3001/api/tracks
Content-Type: application/json
KEY_API:arfhel

{
  "name": "Arfhel",
  "album": "Album",
  "cover": "http://tttt.com",
  "artist": {
    "name": "Arfhel",
    "nickname": "Arfhel V",
    "nationality": "Mxn"
  },
  "duration":{
    "start": 1,
    "end": 0
  },
  "mediaId": "621e7499a1f699063f5114bc" 
}

###Tracks Validator

POST http://localhost:3001/api/tracks
Content-Type: application/json

{
  "name": "Arfhel",
  "cover": "http://tttt.com",
  "artist": {
    "name": "Arfhel",
    "nickname": "Arfhel V",
    "nationality": "Mxn"
  },
  "duration":{
    "start": 1,
    "end": 0
  }
}

###Listar un track

GET http://localhost:3001/api/tracks/65c30e67c15b5faac1cf2b3a

###Actualizar un Track
PATCH http://localhost:3001/api/tracks/65c30e67c15b5faac1cf2b3a
Content-Type: application/json

{
  "dato":"basura",
  "name":"Arfhel",
  "artist":{
    "name":"Arfhel",
    "nickname":"Arfhel",
    "nationality":"Mxn"
  }
}

###Eliminar Track

DELETE http://localhost:3001/api/tracks/65c421f5f7da2f76d34633d5

############################################################### Storage #############################################################

# WARN: No soporta mandar archivos solo queda usar postman
POST http://localhost:3001/api/storage
Content-Type: multipart/form-data

{
  <./1341774.png
}

############################################################### Auth ##################################################################
#####Creacion de usuario

POST http://localhost:3001/api/register
Content-Type: application/json

{
  "name": "Argenis Gutierrez",
  "age": 28,
  "email": "argenis@hotmail.com",
  "password": "argenis123"
}

##### Login

POST http://localhost:3001/api/login
Content-Type: application/json

{
  "email":"argenis@hotmail.com",
  "password": "argenis123"
}

